/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquiringRouteImport } from './routes/acquiring'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as ProductLabRouteImport } from './routes/product-lab'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TestsRouteImport } from './routes/tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquiringRoute = AcquiringRouteImport.update({
  id: '/acquiring',
  path: '/acquiring',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductLabRoute = ProductLabRouteImport.update({
  id: '/product-lab',
  path: '/product-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquiring': typeof AcquiringRoute
  '/brand': typeof BrandRoute
  '/commerce': typeof CommerceRoute
  '/company': typeof CompanyRoute
  '/content': typeof ContentRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/launch': typeof LaunchRoute
  '/product-lab': typeof ProductLabRoute
  '/research': typeof ResearchRoute
  '/suppliers': typeof SuppliersRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquiring': typeof AcquiringRoute
  '/brand': typeof BrandRoute
  '/commerce': typeof CommerceRoute
  '/company': typeof CompanyRoute
  '/content': typeof ContentRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/launch': typeof LaunchRoute
  '/product-lab': typeof ProductLabRoute
  '/research': typeof ResearchRoute
  '/suppliers': typeof SuppliersRoute
  '/tests': typeof TestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquiring': typeof AcquiringRoute
  '/brand': typeof BrandRoute
  '/commerce': typeof CommerceRoute
  '/company': typeof CompanyRoute
  '/content': typeof ContentRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/launch': typeof LaunchRoute
  '/product-lab': typeof ProductLabRoute
  '/research': typeof ResearchRoute
  '/suppliers': typeof SuppliersRoute
  '/tests': typeof TestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquiring'
    | '/brand'
    | '/commerce'
    | '/company'
    | '/content'
    | '/costs'
    | '/dashboard'
    | '/decisions'
    | '/documents'
    | '/inventory'
    | '/launch'
    | '/product-lab'
    | '/research'
    | '/suppliers'
    | '/tests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquiring'
    | '/brand'
    | '/commerce'
    | '/company'
    | '/content'
    | '/costs'
    | '/dashboard'
    | '/decisions'
    | '/documents'
    | '/inventory'
    | '/launch'
    | '/product-lab'
    | '/research'
    | '/suppliers'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/acquiring'
    | '/brand'
    | '/commerce'
    | '/company'
    | '/content'
    | '/costs'
    | '/dashboard'
    | '/decisions'
    | '/documents'
    | '/inventory'
    | '/launch'
    | '/product-lab'
    | '/research'
    | '/suppliers'
    | '/tests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquiringRoute: typeof AcquiringRoute
  BrandRoute: typeof BrandRoute
  CommerceRoute: typeof CommerceRoute
  CompanyRoute: typeof CompanyRoute
  ContentRoute: typeof ContentRoute
  CostsRoute: typeof CostsRoute
  DashboardRoute: typeof DashboardRoute
  DecisionsRoute: typeof DecisionsRoute
  DocumentsRoute: typeof DocumentsRoute
  InventoryRoute: typeof InventoryRoute
  LaunchRoute: typeof LaunchRoute
  ProductLabRoute: typeof ProductLabRoute
  ResearchRoute: typeof ResearchRoute
  SuppliersRoute: typeof SuppliersRoute
  TestsRoute: typeof TestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquiring': {
      id: '/acquiring'
      path: '/acquiring'
      fullPath: '/acquiring'
      preLoaderRoute: typeof AcquiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-lab': {
      id: '/product-lab'
      path: '/product-lab'
      fullPath: '/product-lab'
      preLoaderRoute: typeof ProductLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquiringRoute: AcquiringRoute,
  BrandRoute: BrandRoute,
  CommerceRoute: CommerceRoute,
  CompanyRoute: CompanyRoute,
  ContentRoute: ContentRoute,
  CostsRoute: CostsRoute,
  DashboardRoute: DashboardRoute,
  DecisionsRoute: DecisionsRoute,
  DocumentsRoute: DocumentsRoute,
  InventoryRoute: InventoryRoute,
  LaunchRoute: LaunchRoute,
  ProductLabRoute: ProductLabRoute,
  ResearchRoute: ResearchRoute,
  SuppliersRoute: SuppliersRoute,
  TestsRoute: TestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
